title: Farm Management System
description: A comprehensive OOP demonstration in C#

remote_theme: mmistakes/minimal-mistakes@4.26.2
minimal_mistakes_skin: dark

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
