title: Farm Management System
description: A comprehensive OOP demonstration in C#
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark
# Alternative themes:
# - jekyll-theme-minimal
# - jekyll-theme-slate
# - jekyll-theme-architect

markdown: kramdown
